import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowDown, ArrowUpRight, BriefcaseBusiness, Cloud, Code2, Download, Globe2, Linkedin, Mail, Menu, Network, ShieldCheck, Sparkles, Users, X, CheckCircle2, ChevronRight } from 'lucide-react';

type Project={n:string; category:string; title:string; impact:string; tags:string[]; challenge:string; complexity:string; role:string; approach:string; team:string; outcome:string};
const nav=['Home','About','Journey','Expertise','Projects','Impact','Resume','Contact'];
const metrics=[['19+','Years of experience'],['80+','Professionals led'],['$10M–15M','Annual portfolio'],['95%+','Delivery success'],['98%','SLA compliance']];
const expertise=[['01','Technology & Program Delivery','Turning complex initiatives into governed, predictable execution.',BriefcaseBusiness],['02','Global Delivery Leadership','Leading distributed teams, strategic accounts and enterprise programs.',Globe2],['03','Digital & Cloud Transformation','Modernizing platforms, infrastructure and ways of working.',Cloud],['04','Strategic Client & Stakeholder Management','Creating alignment from executive strategy through delivery teams.',Users],['05','Delivery Governance & Operational Excellence','Strengthening PMO discipline, risk management, KPIs and execution.',ShieldCheck],['06','Technology Strategy, AI & Innovation','Applying architecture, AI and automation to practical business needs.',Sparkles]] as const;
const projects:Project[]=[
['01','Transformation','ERP, Cloud & Digital Transformation','Modernized enterprise platforms while aligning CEO priorities, vendors and technology execution.',['ERP','Shopify','Cloud','SQL','APIs'],'Fragmented legacy applications and infrastructure required modernization without losing business continuity.','Multiple vendors, B2B/e-commerce streams, infrastructure dependencies and executive expectations.','Global Delivery Head / Technical Project Manager','Set a transformation roadmap, governance cadence and integrated vendor-led delivery around measurable priorities.','Cross-functional team and external implementation partners; CEO-level engagement.','Modernization initiatives spanning ERP, cloud, infrastructure, Shopify, B2B/e-commerce and AI-enabled transformation.'],
['02','Global Platform','Global Loyalty Platform','Scaled multi-industry implementations through stronger engineering delivery and technical governance.',['C#','.NET Core','Azure','APIs'],'Enterprise loyalty programs needed consistent delivery across complex integrations and global clients.','Architecture coordination, releases, integrations and stakeholder governance across regions and industries.','Head of Delivery / Technical Project Manager','Combined delivery governance with engineering coordination, release discipline and strategic stakeholder alignment.','80+ delivery organization supporting international programs.','A more scalable operating model for enterprise loyalty implementations and platform evolution.'],
['03','AI Innovation','AI-Powered RFP Automation','Reduced proposal preparation effort with source-backed AI-assisted draft responses.',['OpenAI','LLMs','C#','SQL'],'Incoming RFPs required teams to repeatedly search approved enterprise knowledge and draft responses under time pressure.','Knowledge retrieval quality, source traceability and practical adoption mattered as much as the model output.','Head of Delivery / Solution Designer / Developer','Designed an AI workflow to analyze RFPs, retrieve approved knowledge and generate source-backed drafts.','Focused innovation build for account and RFP stakeholders.','Faster proposal preparation and a reusable foundation for enterprise knowledge automation.'],
['04','Marketplace','Global Loyalty Marketplace','Coordinated a global rewards marketplace across points, miles, gift cards and brand APIs.',['C#','SQL','MVC','.NET Core','APIs'],'Users needed to redeem, manage and exchange multiple loyalty currencies across brands and programs.','High integration density, global releases, resource planning and stakeholder coordination.','Head of Delivery','Established delivery governance around engineering execution, integrations, releases and resource planning.','40+ professionals across delivery and stakeholders.','A governed global platform delivery model supporting complex reward marketplace capabilities.'],
['05','Employee Experience','Employee Engagement & Rewards Platform','Delivered recognition and rewards capabilities across automated points, gift cards and milestone programs.',['C#','SQL','MVC','.NET Core','APIs'],'Organizations needed scalable employee engagement workflows across recognition, rewards and global fulfillment.','Cross-functional integrations and release coordination across a product with multiple engagement journeys.','Head of Delivery','Coordinated technology delivery, integrations, releases and stakeholder governance.','Cross-functional engineering and delivery teams.','Reliable delivery of automated recognition and milestone-based engagement programs.'],
['06','Banking & Risk','Enterprise Banking Risk & Delivery Systems','Led technical delivery across risk, resource/project management and AI/ML due diligence solutions.',['C#','Azure','Python','BERT','OCR'],'Financial-services teams required specialized systems for risk visibility, delivery planning and document intelligence.','Small expert teams, technical architecture and high domain sensitivity.','Delivery Manager / Project Manager / Tech Lead / Technical Architect','Balanced hands-on technical leadership with delivery management and architecture oversight.','Specialist teams of 3–5 professionals across initiatives.','Improved technical delivery control across risk, planning and AI-assisted due diligence work.'],
['07','Security','Enterprise Security & Risk Platforms','Built on deep engineering foundations in automated IT risk assessment and privileged identity management.',['C#','ASP.NET','SQL','Angular','Azure','Jenkins'],'Banking customers needed stronger controls over IT risks, privileged identities and regulatory compliance.','Cross-technology connectors, enterprise integrations, scalable architecture and security controls.','Project Manager / Technical Lead / Senior Software Developer','Led technical evolution, integrations and delivery of enterprise risk and access-control capabilities.','Teams up to 12 across product and engineering functions.','Platforms supporting automated risk assessment, controlled privileged access and compliance-oriented governance.']
].map(([n,category,title,impact,tags,challenge,complexity,role,approach,team,outcome])=>({n,category,title,impact,tags,challenge,complexity,role,approach,team,outcome}));
const journey=[
['TRANSFORM','2025–Present','Mireya UK Ltd.','Global Delivery Head','Technology transformation across ERP modernization, B2B/e-commerce, cloud migration, vendor implementations and AI-enabled initiatives.'],
['SCALE','2020–2025','Giift Plus India Pvt. Ltd.','Head of Delivery – Professional Services','Global portfolio, delivery governance, enterprise loyalty platforms, AI transformation and teams of 80+ professionals.'],
['LEAD','2019–2020','eClerx Services Ltd.','Sr. Consultant – Software Services','Delivery and technical leadership for banking risk, resource/project management and AI/ML due diligence initiatives.'],
['LEAD','2012–2019','ARCON Tech / ANB Solutions','Project Manager / Technical Lead','Enterprise risk, security and privileged access products for domestic and international banking environments.'],
['BUILD','2010–2012','Sureprep India Pvt. Ltd.','Sr. Software Developer','Workflow and document automation engineering for tax preparation technology.'],
['BUILD','2009–2010','Visual Softtech Pvt. Ltd.','Sr. Software Developer','Hospital automation and e-commerce application development.'],
['BUILD','2007–2009','Comnet Solutions Pvt. Ltd.','Software Developer','Web-based helpdesk, incident and asset management software.'],
['BUILD','2007','Mastercard / Finicity lineage','Associate Software Engineer','Early engineering foundation in financial software and digital budgeting systems.']
];
const contactSchema=z.object({name:z.string().min(2),company:z.string().min(2),email:z.string().email(),phone:z.string().optional(),subject:z.string().min(3),message:z.string().min(10)}); type Contact=z.infer<typeof contactSchema>;
function App(){const [menu,setMenu]=useState(false);const [project,setProject]=useState<Project|null>(null);const [cvGate,setCvGate]=useState(false);const [cvEmail,setCvEmail]=useState('');const {register,handleSubmit,formState:{errors}}=useForm<Contact>({resolver:zodResolver(contactSchema)});
const scroll=(id:string)=>document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:'smooth'});
const submit=(d:Contact)=>{const body=`Name: ${d.name}\nCompany: ${d.company}\nEmail: ${d.email}\nPhone: ${d.phone||''}\n\n${d.message}`;window.location.href=`mailto:yogeshw.1711@gmail.com?subject=${encodeURIComponent(d.subject)}&body=${encodeURIComponent(body)}`};
const download=()=>{if(!z.string().email().safeParse(cvEmail).success)return;const a=document.createElement('a');a.href='/Yogesh-Wagh-26-August-2026.pdf';a.download='Yogesh-Wagh-26-August-2026.pdf';a.click();setCvGate(false)};
return <><header><nav className="nav"><button className="brand" onClick={()=>scroll('home')}><b>YW</b><span>YOGESH WAGH</span></button><div className="links">{nav.map(n=><button key={n} onClick={()=>scroll(n)}>{n}</button>)}</div><button className="hire" onClick={()=>scroll('contact')}>HIRE ME <ArrowUpRight size={15}/></button><button className="mobile" onClick={()=>setMenu(!menu)} aria-label="Open menu"><Menu/></button></nav><AnimatePresence>{menu&&<motion.div className="mobilemenu" initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}>{nav.map(n=><button key={n} onClick={()=>{scroll(n);setMenu(false)}}>{n}</button>)}</motion.div>}</AnimatePresence></header>
<main>
<section id="home" className="hero"><div className="hero-copy"><motion.p className="eyebrow" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>GLOBAL TECHNOLOGY & DELIVERY LEADER</motion.p><motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.08}}>Turning Complex Technology<br/>Into <em>Business Outcomes.</em></motion.h1><motion.p className="lead" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.16}}>Technology, program and global delivery leadership with 19+ years of experience connecting business strategy, technology, people and execution.</motion.p><motion.div className="actions" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.24}}><button className="primary" onClick={()=>scroll('contact')}>Hire Me <ArrowUpRight size={17}/></button><button className="secondary" onClick={()=>scroll('journey')}>Explore My Journey <ChevronRight size={17}/></button></motion.div><button className="downloadtext" onClick={()=>setCvGate(true)}><ArrowDown size={16}/> Download CV</button></div><motion.div className="portrait-wrap" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.7}}><div className="portrait-shape"></div><div className="goldline"></div><img src="/assets/yogesh-wagh.jpg" alt="Yogesh Wagh professional portrait"/><motion.div className="availability" animate={{y:[0,-6,0]}} transition={{duration:3,repeat:Infinity}}><span></span> OPEN TO THE RIGHT<br/>LEADERSHIP OPPORTUNITY</motion.div></motion.div></section>
<section className="metrics">{metrics.map(([n,l],i)=><motion.div key={l} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><strong>{n}</strong><span>{l}</span></motion.div>)}</section>
<section id="about" className="section story"><div><p className="kicker">ABOUT / MY STORY</p><h2>MORE THAN<br/><em>PROJECT DELIVERY.</em></h2></div><div className="storycopy"><p>I started with a hands-on engineering foundation and grew through software development, technical leadership and project management into program, global delivery and transformation leadership.</p><p>Today, my work sits at the intersection of technology, people and business—leading enterprise applications, global teams, client relationships, delivery governance, cloud modernization, AI and automation, financial accountability and strategic change.</p><blockquote>“Great delivery happens when strategy, technology, people and execution move in the same direction.”</blockquote></div></section>
<section id="journey" className="section"><p className="kicker">CAREER JOURNEY</p><h2>THE JOURNEY BEHIND<br/>THE <em>LEADERSHIP.</em></h2><div className="timeline">{journey.map(([stage,years,company,role,impact],i)=><motion.article className="milestone" key={company} initial={{opacity:0,x:i%2?40:-40}} whileInView={{opacity:1,x:0}} viewport={{once:true}}><span className="stage">{stage}</span><div className="dot"></div><div className="milecard"><small>{years}</small><h3>{company}</h3><b>{role}</b><p>{impact}</p><details><summary>Explore Role <ChevronRight size={15}/></summary><p>Career progression: strengthened leadership scope through engineering foundations, delivery ownership, architecture coordination, governance, global stakeholder management and transformation leadership.</p></details></div></motion.article>)}</div></section>
<section id="expertise" className="section"><p className="kicker">WHAT I DO</p><h2>WHERE I CREATE <em>IMPACT.</em></h2><div className="expertise-grid">{expertise.map(([n,t,d,Icon])=><motion.article key={t} whileHover={{y:-7}}><span>{n}</span><Icon/><h3>{t}</h3><p>{d}</p></motion.article>)}</div></section>
<section id="projects" className="section projects"><p className="kicker">SELECTED PROJECTS</p><h2>COMPLEX PROBLEMS.<br/><em>PRACTICAL DELIVERY.</em></h2><p className="intro">A curated portfolio of anonymized enterprise challenges across transformation, loyalty, AI, banking risk, security and engineering platforms.</p><div className="project-grid">{projects.map(p=><motion.button layoutId={`p-${p.n}`} className="project" key={p.n} onClick={()=>setProject(p)} whileHover={{y:-5}}><span>{p.n} / {p.category}</span><h3>{p.title}</h3><p>{p.impact}</p><div>{p.tags.map(t=><i key={t}>{t}</i>)}</div><b>Explore story <ArrowUpRight size={16}/></b></motion.button>)}</div></section>
<section id="impact" className="impact"><div><p className="kicker light">LEADERSHIP MEASURED BY OUTCOMES</p><h2>OUTCOMES THAT<br/><em>MOVE THE BUSINESS.</em></h2></div><div className="impact-grid">{[['20%','Improved delivery predictability'],['30%','Reduced release cycles'],['15%','Operational cost optimization'],['95%+','Delivery success'],['98%','SLA compliance'],['$10M–15M','Portfolio leadership'],['80+','Professionals led']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>
<section className="section toolkit"><p className="kicker">CORE EXPERTISE ECOSYSTEM</p><h2>THE LEADERSHIP <em>TOOLKIT.</em></h2>{[['Delivery & Leadership',['Program Management','Global Delivery','Delivery Governance','PMO Leadership','Stakeholder Management','Vendor Management','Risk Management','Team Leadership']],['Technology & Transformation',['Cloud Modernization','Enterprise Applications','Digital Transformation','ERP','AI & Automation','DevOps','CI/CD','API Integration']],['Engineering Foundation',['C#','.NET / .NET Core','SQL','Angular','Python','Azure','AWS','Enterprise SaaS']],['Business & Strategy',['P&L Ownership','Financial Governance','Resource Optimization','Strategic Accounts','Customer Success','Presales','RFP Leadership','Technology Roadmaps']]].map(([title,items])=><div className="skillgroup" key={title as string}><h3>{title as string}</h3><div>{(items as string[]).map(x=><span key={x}>{x}</span>)}</div></div>)}</section>
<section className="section philosophy"><p className="kicker">LEADERSHIP PHILOSOPHY</p><h2>HOW I <em>LEAD.</em></h2><div className="principles">{[['CLARITY','Clear priorities, ownership and communication.'],['ACCOUNTABILITY','Creating ownership while enabling teams to succeed.'],['COLLABORATION','Connecting business, technology, clients and delivery teams.'],['CONTINUOUS IMPROVEMENT','Improving quality, speed, efficiency and outcomes.']].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div><blockquote>“Leadership is not about controlling every detail. It is about creating clarity, building trust, removing obstacles and enabling people to deliver their best work.”</blockquote></section>
<section className="section credentials"><p className="kicker">PROFESSIONAL CREDENTIALS</p><h2>BUILT ON EXPERIENCE.<br/><em>STRENGTHENED BY LEARNING.</em></h2><div className="credential-grid"><article><CheckCircle2/><h3>M.Sc. in Computer Science</h3><p>Thakur College / Mumbai University</p></article><article><CheckCircle2/><h3>PMP</h3><p>Project Management Professional</p></article><article><CheckCircle2/><h3>Certified ScrumMaster®</h3><p>Scrum Alliance</p></article><article><CheckCircle2/><h3>Certified Scrum Product Owner®</h3><p>CSPO</p></article></div></section>
<section id="resume" className="section resume"><p className="kicker">MY PROFESSIONAL PROFILE</p><div className="resume-card"><div><h2>YOGESH WAGH</h2><h3>Global Delivery Head | Technology Architect | Fintech | AI | Digital Platforms | SaaS | Cloud | Enterprise Technology</h3><p>19+ years leading global delivery organizations, enterprise programs and strategic accounts across Banking, FinTech, Loyalty, Ecommerce, Security and Enterprise Platforms.</p><div className="resume-highlights"><span>Global delivery across North America, EMEA & APAC</span><span>$10M–15M portfolio ownership</span><span>80+ professionals led</span></div></div><button className="primary" onClick={()=>setCvGate(true)}><Download size={17}/> Download CV</button></div></section>
<section className="opportunity"><p className="kicker">OPEN TO OPPORTUNITIES</p><h2>OPEN TO MEANINGFUL<br/><em>LEADERSHIP OPPORTUNITIES.</em></h2><p>I am interested in opportunities where I can lead complex technology initiatives, strengthen delivery organizations, drive transformation and create measurable business outcomes.</p><div>{['Senior Project Manager','Technical Project Manager','Program Manager','Technical Program Manager','Technology Delivery Manager','IT Delivery Manager','Digital Transformation Manager','Global Delivery Leadership'].map(x=><span key={x}>{x}</span>)}</div><button className="secondary" onClick={()=>scroll('contact')}>Discuss an opportunity <ArrowUpRight size={17}/></button></section>
<section id="contact" className="contact"><div><p className="kicker light">CONTACT / HIRE ME</p><h2>LET'S BUILD SOMETHING<br/>THAT <em>MATTERS.</em></h2><p>Whether you are looking for someone to lead a complex technology program, strengthen delivery operations, manage strategic stakeholders or drive transformation, let's start a conversation.</p><a href="mailto:yogeshw.1711@gmail.com"><Mail size={18}/> yogeshw.1711@gmail.com</a><a href="https://www.linkedin.com/in/yogeshwaghdeliverydirector/" target="_blank" rel="noreferrer"><Linkedin size={18}/> Connect on LinkedIn</a></div><form onSubmit={handleSubmit(submit)}><input placeholder="Full Name" {...register('name')}/><input placeholder="Company" {...register('company')}/><input placeholder="Email" {...register('email')}/><input placeholder="Phone (Optional)" {...register('phone')}/><input placeholder="Subject / Opportunity" {...register('subject')}/><textarea placeholder="Message" {...register('message')}/>{Object.keys(errors).length>0&&<small>Please complete all required fields with a valid email.</small>}<button className="goldbtn">Start a Conversation <ArrowUpRight size={17}/></button></form></section>
</main><footer><div className="brand"><b>YW</b><span>YOGESH WAGH</span></div><p>Global Technology & Delivery Leader</p><div><a href="https://www.linkedin.com/in/yogeshwaghdeliverydirector/" target="_blank">LinkedIn</a><a href="mailto:yogeshw.1711@gmail.com">Email</a></div><small>© {new Date().getFullYear()} Yogesh Wagh. All Rights Reserved.</small></footer>
<AnimatePresence>{project&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setProject(null)}><motion.article initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:20,opacity:0}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setProject(null)}><X/></button><span>{project.n} / {project.category}</span><h2>{project.title}</h2>{[['The Challenge',project.challenge],['The Delivery Complexity',project.complexity],['My Role',project.role],['My Approach',project.approach],['Team / Stakeholders',project.team],['Outcome',project.outcome]].map(([a,b])=><div className="storyblock" key={a}><h4>{a}</h4><p>{b}</p></div>)}</motion.article></motion.div>}</AnimatePresence>
<AnimatePresence>{cvGate&&<motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.article className="gate" initial={{scale:.95}} animate={{scale:1}}><button className="close" onClick={()=>setCvGate(false)}><X/></button><h2>DOWNLOAD CV</h2><p>Please enter your email ID before downloading the latest CV.</p><input autoFocus placeholder="your@email.com" value={cvEmail} onChange={e=>setCvEmail(e.target.value)}/><button className="goldbtn" onClick={download}>Validate & Download <Download size={17}/></button></motion.article></motion.div>}</AnimatePresence>
</>}
export default App;
